name: campus_connect_frontend
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.8.0
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.3.3
  json_serializable: ^6.8.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  copy_with_extension: ^5.0.0
  copy_with_extension_gen: ^5.0.4
  build_runner: ^2.4.11
  auto_size_text: ^3.0.0
  outline_material_icons: ^1.0.0
  loading_animation_widget: ^1.3.0
  file_picker: ^8.1.4
  mime_type: ^1.0.1
  http_parser: ^4.0.2
  dropdown_button2: ^2.3.9
  multi_image_picker_view: ^2.0.0
  uuid: ^4.5.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: Minork
      fonts:
        - asset: fonts/Fontspring-DEMO-minorksans-regular.otf

    - family: MinorkItalic
      fonts:
        - asset: fonts/Fontspring-DEMO-minorksans-italic.otf

    - family: MinorkSemiBold
      fonts:
        - asset: fonts/Fontspring-DEMO-minorksans-semibold.otf

    - family: MinorkSemiBoldItalic
      fonts:
        - asset: fonts/Fontspring-DEMO-minorksans-semibolditalic.otf

    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf

    - family: NunitoItalic
      fonts:
        - asset: fonts/Nunito-Italic.ttf

    - family: NunitoSemiBold
      fonts:
        - asset: fonts/Nunito-SemiBold.ttf

    - family: NunitoSemiBoldItalic
      fonts:
        - asset: fonts/Nunito-SemiBoldItalic.ttf

